import {
  AdminSession,
  AdminStage,
  AdminBooth,
  AdminAnnouncement,
  ZoneDensityInfo,
  AdminAttendee,
  AdminMeetingRecord,
  AdminLogItem,
} from '../types/admin';

export const initialStages: AdminStage[] = [
  {
    id: 'stage-main',
    name: 'Ana Sahne (Hall A)',
    type: 'Main Stage',
    zone: 'Zone A',
    capacity: 1200,
    currentOccupancy: 940,
    mapX: 25,
    mapY: 28,
    status: 'active',
    currentSessionId: 'sess-1',
    description:
      'Etkinliğin ana keynote, küresel panel ve açılış seremonilerinin yapıldığı ana oditoryum.',
  },
  {
    id: 'stage-ai',
    name: 'AI & Derin Teknoloji Sahnesi',
    type: 'AI Stage',
    zone: 'Zone B',
    capacity: 450,
    currentOccupancy: 415,
    mapX: 72,
    mapY: 25,
    status: 'active',
    currentSessionId: 'sess-ai-1',
    description:
      'Büyük dil modelleri, üretken yapay zeka, robotik ve bilgisayarlı görü oturumları.',
  },
  {
    id: 'stage-startup',
    name: 'Startup Pitch Stage',
    type: 'Startup Stage',
    zone: 'Zone C',
    capacity: 350,
    currentOccupancy: 210,
    mapX: 30,
    mapY: 65,
    status: 'active',
    currentSessionId: 'sess-startup-1',
    description: '100+ seçilmiş girişimin yatırımcı jürisine 3 dakikalık sunum yaptığı sahne.',
  },
  {
    id: 'stage-workshop',
    name: 'Hands-on Workshop Lab C',
    type: 'Workshop Area',
    zone: 'Zone B',
    capacity: 120,
    currentOccupancy: 110,
    mapX: 82,
    mapY: 55,
    status: 'active',
    currentSessionId: 'sess-4',
    description: 'Uygulamalı kodlama, bulut mimarileri ve yapay zeka prompt mühendisliği atölyesi.',
  },
  {
    id: 'stage-networking',
    name: 'B2B Networking Lounge',
    type: 'Networking Area',
    zone: 'Zone D',
    capacity: 600,
    currentOccupancy: 380,
    mapX: 60,
    mapY: 78,
    status: 'active',
    description:
      'Girişimci ve yatırımcıların 1:1 planlanmış veya serbest görüşmeler yaptığı lounge.',
  },
  {
    id: 'stage-meeting',
    name: 'VIP Yatırımcı Masaları',
    type: 'Meeting Area',
    zone: 'Zone A',
    capacity: 80,
    currentOccupancy: 55,
    mapX: 18,
    mapY: 48,
    status: 'active',
    description: 'Özel Seri A+ ve fon yöneticisi ikili görüşme alanı.',
  },
  {
    id: 'stage-food',
    name: 'Food Court & Kafe',
    type: 'Food Area',
    zone: 'Zone D',
    capacity: 500,
    currentOccupancy: 310,
    mapX: 85,
    mapY: 82,
    status: 'active',
    description: 'Gurme kahve ve ikram alanı.',
  },
];

export const initialBooths: AdminBooth[] = [
  {
    id: 'booth-1',
    boothNo: 'A101',
    companyName: 'FintechLabs Global',
    category: 'Fintech',
    description: 'Yapay zeka tabanlı açık bankacılık ve mikro-ödeme altyapısı sağlayıcısı.',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    zone: 'Zone A',
    sponsorTier: 'Platinum',
    mapX: 38,
    mapY: 34,
    status: 'active',
    contactPerson: 'Ayşe Yılmaz',
    contactEmail: 'ayse@fintechlabs.io',
    totalVisits: 412,
  },
  {
    id: 'booth-2',
    boothNo: 'A102',
    companyName: 'Cognitive AI Labs',
    category: 'Yapay Zeka',
    description: 'Kurumsal veri tabanları için otonom çoklu-ajan karar sistemleri.',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    zone: 'Zone A',
    sponsorTier: 'Platinum',
    mapX: 44,
    mapY: 34,
    status: 'active',
    contactPerson: 'Zeynep Aksoy',
    contactEmail: 'zeynep@cognitiveai.com',
    totalVisits: 620,
  },
  {
    id: 'booth-3',
    boothNo: 'B201',
    companyName: 'CloudSync Enterprise',
    category: 'SaaS',
    description: 'Çoklu-bulut veri transferi ve gerçek zamanlı felaket kurtarma platformu.',
    logo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=150&q=80',
    zone: 'Zone B',
    sponsorTier: 'Gold',
    mapX: 68,
    mapY: 42,
    status: 'active',
    contactPerson: 'Selin Demir',
    contactEmail: 'selin@cloudsync.io',
    totalVisits: 295,
  },
  {
    id: 'booth-4',
    boothNo: 'B202',
    companyName: 'MedPulse Diagnostics',
    category: 'Sağlık Teknolojileri',
    description: 'Yapay zeka destekli erken teşhis görüntüleme ve biyosensör donanımları.',
    logo: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=150&q=80',
    zone: 'Zone B',
    sponsorTier: 'Gold',
    mapX: 75,
    mapY: 42,
    status: 'active',
    contactPerson: 'Dr. Caner Kaya',
    contactEmail: 'caner@medpulse.health',
    totalVisits: 340,
  },
  {
    id: 'booth-5',
    boothNo: 'C301',
    companyName: 'EcoGrid Dynamics',
    category: 'Sürdürülebilirlik',
    description: 'Endüstriyel tesisler için akıllı enerji tüketim optimizasyonu.',
    logo: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=150&q=80',
    zone: 'Zone C',
    sponsorTier: 'Startup',
    mapX: 28,
    mapY: 78,
    status: 'active',
    contactPerson: 'Deniz Arslan',
    contactEmail: 'deniz@ecogrid.tech',
    totalVisits: 185,
  },
  {
    id: 'booth-6',
    boothNo: 'C302',
    companyName: 'RoboLogix Automation',
    category: 'Donanım & IoT',
    description: 'E-ticaret depoları için otonom yönlendirmeli taşıma robotları.',
    logo: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=150&q=80',
    zone: 'Zone C',
    sponsorTier: 'Startup',
    mapX: 35,
    mapY: 78,
    status: 'active',
    contactPerson: 'Emre Yıldız',
    contactEmail: 'emre@robologix.ai',
    totalVisits: 220,
  },
  {
    id: 'booth-7',
    boothNo: 'D401',
    companyName: 'VentureScale Capital',
    category: 'Yatırım / VC',
    description: 'Erken aşama B2B DeepTech ve SaaS girişimlerine 500K$-3M$ tohum fonu.',
    logo: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=150&q=80',
    zone: 'Zone D',
    sponsorTier: 'Partner',
    mapX: 52,
    mapY: 88,
    status: 'active',
    contactPerson: 'Caner Kaya',
    contactEmail: 'contact@venturescale.vc',
    totalVisits: 510,
  },
];

export const initialAdminSessions: AdminSession[] = [
  {
    id: 'sess-1',
    day: '24',
    dayName: 'Cum',
    dateStr: '24 Ekim 2026',
    time: '14:00',
    endTime: '14:45',
    duration: '45dk',
    category: 'Keynote',
    title: 'AI & Future of Entrepreneurship: Küresel Teknoloji Vizyonu',
    description:
      'TakeOff Summit açılış seremonisi ve küresel üretken yapay zeka pazarının geleceği.',
    stageId: 'stage-main',
    stageName: 'Ana Sahne (Hall A)',
    speakers: [
      {
        id: 'sp-1',
        name: 'Dr. Kerem Tan',
        title: 'Baş Danışman & AI Stratejisti',
        company: 'AI World Council',
        avatar:
          'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
      },
    ],
    status: 'live',
    capacity: 1200,
    bookmarkedCount: 680,
    checkedInCount: 940,
    tags: ['Yapay Zeka', 'Açılış', 'Global Vizyon'],
  },
  {
    id: 'sess-ai-1',
    day: '24',
    dayName: 'Cum',
    dateStr: '24 Ekim 2026',
    time: '14:15',
    endTime: '15:00',
    duration: '45dk',
    category: 'Panel',
    title: 'Büyük Dil Modelleri ve Çoklu-Ajan Mimarileri',
    description: 'Üretim ortamında güvenilir LLM ajanları kurma stratejileri ve vaka analizleri.',
    stageId: 'stage-ai',
    stageName: 'AI & Derin Teknoloji Sahnesi',
    speakers: [
      {
        id: 'sp-2',
        name: 'Zeynep Aksoy',
        title: 'Kurucu Ortak',
        company: 'Cognitive AI Labs',
        avatar:
          'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=200&q=80',
      },
    ],
    status: 'live',
    capacity: 450,
    bookmarkedCount: 390,
    checkedInCount: 415,
    tags: ['GenAI', 'LLM Agents', 'Derin Teknoloji'],
  },
  {
    id: 'sess-startup-1',
    day: '24',
    dayName: 'Cum',
    dateStr: '24 Ekim 2026',
    time: '15:15',
    endTime: '16:30',
    duration: '75dk',
    category: 'Pitch',
    title: 'TakeOff Top 20 Startup Pitching - Round 1',
    description: '20 seçilmiş erken aşama girişimin 3 dakikalık canlı jüri sunumları.',
    stageId: 'stage-startup',
    stageName: 'Startup Pitch Stage',
    speakers: [
      {
        id: 'sp-3',
        name: 'Caner Kaya',
        title: 'Jüri Başkanı & VC',
        company: 'VentureScale Partners',
        avatar:
          'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
      },
    ],
    status: 'published',
    capacity: 350,
    bookmarkedCount: 310,
    checkedInCount: 0,
    tags: ['Pitching', 'Yatırım', 'Girişimcilik'],
  },
  {
    id: 'sess-4',
    day: '24',
    dayName: 'Cum',
    dateStr: '24 Ekim 2026',
    time: '15:30',
    endTime: '16:30',
    duration: '60dk',
    category: 'Workshop',
    title: 'Kendi Yapay Zeka Modelini Eğitmek ve Dağıtmak',
    description:
      'Hands-on atölye: Özel veri setleri ile domain modelleri eğitme ve bulutta çalıştırma.',
    stageId: 'stage-workshop',
    stageName: 'Hands-on Workshop Lab C',
    speakers: [
      {
        id: 'sp-4',
        name: 'Ahmet Yılmaz',
        title: 'Kıdemli Yazılım Mühendisi',
        company: 'TechNovation',
        avatar:
          'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
      },
    ],
    status: 'delayed',
    delayMinutes: 15,
    capacity: 120,
    bookmarkedCount: 142,
    checkedInCount: 95,
    tags: ['Hands-on', 'AI Kodlama', 'Cloud'],
  },
  {
    id: 'sess-main-2',
    day: '24',
    dayName: 'Cum',
    dateStr: '24 Ekim 2026',
    time: '16:45',
    endTime: '17:45',
    duration: '60dk',
    category: 'Panel',
    title: 'Startup Investment Panel: 2026 VC Trendleri',
    description:
      'Bölgesel ve global fon liderlerinin tohumdan büyüme aşamasına yatırım beklentileri.',
    stageId: 'stage-main',
    stageName: 'Ana Sahne (Hall A)',
    speakers: [
      {
        id: 'sp-5',
        name: 'Ayşe Saygın',
        title: 'Yatırım Direktörü',
        company: 'Horizon VC',
        avatar:
          'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
      },
      {
        id: 'sp-6',
        name: 'Mehmet Yılmaz',
        title: 'CEO',
        company: 'TechCorp Global',
        avatar:
          'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&q=80',
      },
    ],
    status: 'published',
    capacity: 1200,
    bookmarkedCount: 520,
    checkedInCount: 0,
    tags: ['Yatırım', 'VC', 'Panel'],
  },
  // Day 25
  {
    id: 'sess-d2-1',
    day: '25',
    dayName: 'Cmt',
    dateStr: '25 Ekim 2026',
    time: '10:00',
    endTime: '10:50',
    duration: '50dk',
    category: 'Panel',
    title: 'Fintech ve Açık Bankacılıkta Yeni Ufuklar',
    description: 'Gömülü finans, yapay zeka ile kredi skorlama ve yeni nesil ödeme sistemleri.',
    stageId: 'stage-main',
    stageName: 'Ana Sahne (Hall A)',
    speakers: [
      {
        id: 'sp-7',
        name: 'Ayşe Yılmaz',
        title: 'Yazılım Mühendisi',
        company: 'FintechLabs',
        avatar:
          'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
      },
    ],
    status: 'published',
    capacity: 1200,
    bookmarkedCount: 380,
    checkedInCount: 0,
    tags: ['Fintech', 'Açık Bankacılık'],
  },
  {
    id: 'sess-d2-2',
    day: '25',
    dayName: 'Cmt',
    dateStr: '25 Ekim 2026',
    time: '11:30',
    endTime: '12:30',
    duration: '60dk',
    category: 'Fireside Chat',
    title: 'Unicorn Kurucularının Başarı ve Hata Hikayeleri',
    description: 'İlk 100 müşteriden milyar dolarlık değerlemeye giden yolda kurucu tecrübeleri.',
    stageId: 'stage-ai',
    stageName: 'AI & Derin Teknoloji Sahnesi',
    speakers: [
      {
        id: 'sp-8',
        name: 'Mehmet Yılmaz',
        title: 'CEO',
        company: 'TechCorp Global',
        avatar:
          'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&q=80',
      },
    ],
    status: 'published',
    capacity: 450,
    bookmarkedCount: 420,
    checkedInCount: 0,
    tags: ['Unicorn', 'Fireside Chat', 'Girişimcilik'],
  },
  {
    id: 'sess-d2-3',
    day: '25',
    dayName: 'Cmt',
    dateStr: '25 Ekim 2026',
    time: '14:00',
    endTime: '15:30',
    duration: '90dk',
    category: 'Pitch',
    title: 'Global Investors Demo Day & Pitch Finals',
    description: 'Büyük final sunumları ve uluslararası jüri değerlendirmesi.',
    stageId: 'stage-startup',
    stageName: 'Startup Pitch Stage',
    speakers: [],
    status: 'published',
    capacity: 350,
    bookmarkedCount: 490,
    checkedInCount: 0,
    tags: ['Demo Day', 'Final', 'Pitch'],
  },
];

export const initialZones: ZoneDensityInfo[] = [
  {
    id: 'zone-a',
    name: 'Zone A - Ana Oditoryum & VIP',
    code: 'Zone A',
    activeAttendees: 1020,
    capacity: 1400,
    densityLevel: 'Orta',
    densityPercent: 73,
    peakAttendees: 1180,
    avgAttendees: 890,
    description: 'Ana Sahne, Protokol Girişi ve VIP Yatırımcı Locası alanını kapsar.',
    color: '#3b82f6',
    centerLat: null,
    centerLng: null,
    radiusMeters: 60,
  },
  {
    id: 'zone-b',
    name: 'Zone B - AI Sahnesi & Teknoloji Pavyonu',
    code: 'Zone B',
    activeAttendees: 560,
    capacity: 650,
    densityLevel: 'Yoğun',
    densityPercent: 86,
    peakAttendees: 620,
    avgAttendees: 480,
    description: 'AI Sahnesi, Hands-on Lab C ve Derin Teknoloji Stantları.',
    color: '#c85000',
    centerLat: null,
    centerLng: null,
    radiusMeters: 60,
  },
  {
    id: 'zone-c',
    name: 'Zone C - Girişim Stantları & Pitch Sahnesi',
    code: 'Zone C',
    activeAttendees: 440,
    capacity: 600,
    densityLevel: 'Normal',
    densityPercent: 73,
    peakAttendees: 510,
    avgAttendees: 370,
    description: '100+ Erken Aşama Girişim Stantları ve Pitch Sahnesi.',
    color: '#10b981',
    centerLat: null,
    centerLng: null,
    radiusMeters: 60,
  },
  {
    id: 'zone-d',
    name: 'Zone D - B2B Networking & Food Lounge',
    code: 'Zone D',
    activeAttendees: 690,
    capacity: 1100,
    densityLevel: 'Normal',
    densityPercent: 63,
    peakAttendees: 880,
    avgAttendees: 600,
    description: 'B2B Toplantı Masaları, Kahve İkram Alanı ve Açık Teras.',
    color: '#8b5cf6',
    centerLat: null,
    centerLng: null,
    radiusMeters: 60,
  },
];

export const initialAnnouncements: AdminAnnouncement[] = [
  {
    id: 'ann-1',
    title: 'AI Sahnesinde Büyük İlgi & Kapasite Bilgisi',
    message:
      "AI & Derin Teknoloji sahnesi oturumu için salon doluluğu %90'a ulaşmıştır. Dilerseniz fuayedeki canlı ekranlardan yayını takip edebilirsiniz.",
    targetAudience: 'Tüm Katılımcılar',
    sentAt: '24 Ekim 2026, 14:10',
    status: 'sent',
    recipientCount: 2420,
    readCount: 1890,
    clickCount: 420,
  },
  {
    id: 'ann-2',
    title: 'Hands-on Workshop Saati Güncellendi',
    message:
      'Lab C salonundaki "Kendi Yapay Zeka Modelini Eğitmek" workshop oturumu teknik hazırlık sebebiyle 15:45\'te başlayacaktır.',
    targetAudience: 'Oturumu Kaydedenler',
    targetSessionId: 'sess-4',
    sentAt: '24 Ekim 2026, 13:45',
    status: 'sent',
    recipientCount: 142,
    readCount: 138,
    clickCount: 65,
  },
  {
    id: 'ann-3',
    title: 'Top 20 Startup Pitch Başlıyor!',
    message:
      'Startup Pitch Stage alanında 3 dakikalık girişimci sunumları ve canlı yatırımcı oylaması 15 dakika içinde başlıyor.',
    targetAudience: 'Yatırımcılar',
    scheduledFor: '24 Ekim 2026, 15:00',
    status: 'scheduled',
    recipientCount: 380,
    readCount: 0,
    clickCount: 0,
  },
];

export const initialAttendees: AdminAttendee[] = [
  {
    id: 'att-1',
    firstName: 'Ahmet',
    lastName: 'Yılmaz',
    name: 'Ahmet Yılmaz',
    title: 'Kıdemli Yazılım Mühendisi & Kurucu',
    position: 'Kurucu Ortak & CTO',
    company: 'TechNovation',
    role: 'Girişimci',
    sector: 'Yapay Zeka / SaaS',
    interests: ['Yapay Zeka', 'Blockchain', 'Mobil Geliştirme'],
    avatar:
      'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    email: 'ahmet@technovation.co',
    phone: '+90 532 555 0192',
    linkedin: 'linkedin.com/in/ahmetyilmaz-tech',
    status: 'active',
    agendaCount: 6,
    meetingsCount: 4,
    checkInCount: 3,
    lastActive: '3 dakika önce',
    currentZone: 'Zone B',
    badgeScanned: true,
    createdAt: '12 Ekim 2026',
  },
  {
    id: 'att-2',
    firstName: 'Ayşe',
    lastName: 'Saygın',
    name: 'Ayşe Saygın',
    title: 'Yatırım Direktörü',
    position: 'Yatırım Direktörü',
    company: 'Horizon VC',
    role: 'Yatırımcı',
    sector: 'Fintech & DeepTech',
    interests: ['Fintech', 'Seri A', 'Tohum Yatırım'],
    avatar:
      'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    email: 'ayse.saygin@horizonvc.com',
    phone: '+90 533 111 4488',
    linkedin: 'linkedin.com/in/aysesaygin-vc',
    status: 'active',
    agendaCount: 8,
    meetingsCount: 12,
    checkInCount: 5,
    lastActive: 'Şimdi aktif',
    currentZone: 'Zone A',
    badgeScanned: true,
    createdAt: '14 Ekim 2026',
  },
  {
    id: 'att-3',
    firstName: 'Caner',
    lastName: 'Kaya',
    name: 'Caner Kaya',
    title: 'Melek Yatırımcı & Partner',
    position: 'Genel Partner',
    company: 'VentureScale Partners',
    role: 'Yatırımcı',
    sector: 'Sağlık & B2B SaaS',
    interests: ['Tohum Yatırım', 'Seri A', 'Sağlık Teknolojileri'],
    avatar:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    email: 'caner@venturescale.vc',
    phone: '+90 542 999 3322',
    linkedin: 'linkedin.com/in/canerkaya-invest',
    status: 'active',
    agendaCount: 5,
    meetingsCount: 9,
    checkInCount: 4,
    lastActive: '12 dakika önce',
    currentZone: 'Zone D',
    badgeScanned: true,
    createdAt: '15 Ekim 2026',
  },
  {
    id: 'att-4',
    firstName: 'Zeynep',
    lastName: 'Aksoy',
    name: 'Zeynep Aksoy',
    title: 'Yapay Zeka Araştırmacısı & Kurucu',
    position: 'CEO & Yapay Zeka Lideri',
    company: 'Cognitive AI Labs',
    role: 'Girişimci',
    sector: 'Yapay Zeka & Derin Teknoloji',
    interests: ['GenAI', 'Otonom Ajanlar', 'SaaS'],
    avatar:
      'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=200&q=80',
    email: 'zeynep@cognitiveai.com',
    phone: '+90 535 222 7711',
    linkedin: 'linkedin.com/in/zeynepaksoy-ai',
    status: 'active',
    agendaCount: 4,
    meetingsCount: 6,
    checkInCount: 4,
    lastActive: '1 dakika önce',
    currentZone: 'Zone B',
    badgeScanned: true,
    createdAt: '16 Ekim 2026',
  },
  {
    id: 'att-5',
    firstName: 'Mehmet',
    lastName: 'Yılmaz',
    name: 'Mehmet Yılmaz',
    title: 'CEO & Yönetim Kurulu Başkanı',
    position: 'Genel Müdür',
    company: 'TechCorp Global',
    role: 'Kurum / Partner',
    sector: 'Kurumsal Teknoloji',
    interests: ['Stratejik Ortaklıklar', 'Global İhracat'],
    avatar:
      'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&q=80',
    email: 'mehmet.yilmaz@techcorp.com',
    phone: '+90 530 444 8822',
    linkedin: 'linkedin.com/in/mehmetyilmaz-corp',
    status: 'active',
    agendaCount: 7,
    meetingsCount: 8,
    checkInCount: 3,
    lastActive: '15 dakika önce',
    currentZone: 'Zone A',
    badgeScanned: true,
    createdAt: '18 Ekim 2026',
  },
  {
    id: 'att-6',
    firstName: 'Burak',
    lastName: 'Çelik',
    name: 'Burak Çelik',
    title: 'Pazarlama & Büyüme Direktörü',
    position: 'Büyüme Danışmanı',
    company: 'GrowthMinds',
    role: 'Ziyaretçi',
    sector: 'Dijital Pazarlama & Medya',
    interests: ['SaaS Büyüme', 'İşe Alım'],
    avatar:
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    email: 'burak@growthminds.agency',
    phone: '+90 544 333 1100',
    linkedin: 'linkedin.com/in/burakcelik-growth',
    status: 'active',
    agendaCount: 3,
    meetingsCount: 2,
    checkInCount: 2,
    lastActive: '45 dakika önce',
    currentZone: 'Zone C',
    badgeScanned: true,
    createdAt: '19 Ekim 2026',
  },
  {
    id: 'att-7',
    firstName: 'Selin',
    lastName: 'Demir',
    name: 'Selin Demir',
    title: 'Ürün Yönetimi Direktörü',
    position: 'VP of Product',
    company: 'CloudSync Enterprise',
    role: 'Kurum / Partner',
    sector: 'Bulut & Veri Altyapısı',
    interests: ['B2B SaaS', 'Ürün Büyümesi'],
    avatar:
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    email: 'selin@cloudsync.io',
    phone: '+90 532 888 1234',
    linkedin: 'linkedin.com/in/selindemir-product',
    status: 'active',
    agendaCount: 5,
    meetingsCount: 5,
    checkInCount: 3,
    lastActive: '5 dakika önce',
    currentZone: 'Zone B',
    badgeScanned: true,
    createdAt: '20 Ekim 2026',
  },
  {
    id: 'att-8',
    firstName: 'Emre',
    lastName: 'Öztürk',
    name: 'Emre Öztürk',
    title: 'Fintech Girişimcisi & CEO',
    position: 'Kurucu & CEO',
    company: 'PayFlow Technologies',
    role: 'Girişimci',
    sector: 'Finansal Teknolojiler',
    interests: ['Açık Bankacılık', 'Ödeme Sistemleri', 'RegTech'],
    avatar:
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80',
    email: 'emre@payflow.tech',
    phone: '+90 537 777 9900',
    linkedin: 'linkedin.com/in/emreozturk-fintech',
    status: 'active',
    agendaCount: 4,
    meetingsCount: 7,
    checkInCount: 2,
    lastActive: '1 saat önce',
    currentZone: 'Zone C',
    badgeScanned: true,
    createdAt: '21 Ekim 2026',
  },
  {
    id: 'att-9',
    firstName: 'Deniz',
    lastName: 'Vural',
    name: 'Deniz Vural',
    title: 'İnovasyon Müdürü',
    position: 'Kurumsal İnovasyon Lideri',
    company: 'Anadolu Sigorta İnovasyon',
    role: 'Kurum / Partner',
    sector: 'Sigorta & InsurTech',
    interests: ['Kurumsal Girişim Sermayesi', 'InsurTech', 'IoT'],
    avatar:
      'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
    email: 'deniz.vural@anadolusigorta.com.tr',
    phone: '+90 533 666 4321',
    linkedin: 'linkedin.com/in/denizvural-innovation',
    status: 'passive',
    agendaCount: 2,
    meetingsCount: 1,
    checkInCount: 0,
    lastActive: '1 gün önce',
    currentZone: 'Giriş Yapılmadı',
    badgeScanned: false,
    createdAt: '22 Ekim 2026',
  },
  {
    id: 'att-10',
    firstName: 'Kaan',
    lastName: 'Ertekin',
    name: 'Kaan Ertekin',
    title: 'Teknoloji Yazarı & Analist',
    position: 'Teknoloji Editörü',
    company: 'TechTrends Medya',
    role: 'Ziyaretçi',
    sector: 'Medya & Gazetecilik',
    interests: ['Erken Aşama Girişimler', 'Mobil Uygulamalar'],
    avatar:
      'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=200&q=80',
    email: 'kaan.ertekin@techtrends.com',
    phone: '+90 541 222 8844',
    linkedin: 'linkedin.com/in/kaanertekin-media',
    status: 'active',
    agendaCount: 6,
    meetingsCount: 0,
    checkInCount: 2,
    lastActive: '20 dakika önce',
    currentZone: 'Zone A',
    badgeScanned: true,
    createdAt: '22 Ekim 2026',
  },
];

export const initialMeetingRecords: AdminMeetingRecord[] = [
  {
    id: 'm-rec-1',
    date: '24 Ekim 2026',
    timeSlot: '14:30 - 15:00',
    participantA: {
      id: 'att-1',
      name: 'Ahmet Yılmaz',
      role: 'Girişimci',
      company: 'TechNovation',
      avatar:
        'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    },
    participantB: {
      id: 'att-2',
      name: 'Ayşe Saygın',
      role: 'Yatırımcı',
      company: 'Horizon VC',
      avatar:
        'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    },
    tableLocation: 'B2B Lounge - Masa 04',
    status: 'accepted',
    note: 'Tohum sonrası Seri A finansman turu görüşmesi.',
  },
  {
    id: 'm-rec-2',
    date: '24 Ekim 2026',
    timeSlot: '15:15 - 15:45',
    participantA: {
      id: 'att-4',
      name: 'Zeynep Aksoy',
      role: 'Girişimci',
      company: 'Cognitive AI Labs',
      avatar:
        'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=200&q=80',
    },
    participantB: {
      id: 'att-3',
      name: 'Caner Kaya',
      role: 'Yatırımcı',
      company: 'VentureScale Partners',
      avatar:
        'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    },
    tableLocation: 'B2B Lounge - Masa 08',
    status: 'accepted',
    note: 'Derin teknoloji fonlama şartları.',
  },
  {
    id: 'm-rec-3',
    date: '24 Ekim 2026',
    timeSlot: '16:00 - 16:30',
    participantA: {
      id: 'att-6',
      name: 'Burak Çelik',
      role: 'Ziyaretçi',
      company: 'GrowthMinds',
      avatar:
        'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    },
    participantB: {
      id: 'att-5',
      name: 'Mehmet Yılmaz',
      role: 'Kurum / Partner',
      company: 'TechCorp Global',
      avatar:
        'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&q=80',
    },
    tableLocation: 'VIP Salon - Masa 02',
    status: 'pending',
    note: 'Kurumsal pazarlama iş birliği.',
  },
  {
    id: 'm-rec-4',
    date: '24 Ekim 2026',
    timeSlot: '17:00 - 17:30',
    participantA: {
      id: 'att-7',
      name: 'Selin Demir',
      role: 'Konuşmacı',
      company: 'CloudSync Enterprise',
      avatar:
        'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    },
    participantB: {
      id: 'att-1',
      name: 'Ahmet Yılmaz',
      role: 'Girişimci',
      company: 'TechNovation',
      avatar:
        'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    },
    tableLocation: 'B2B Lounge - Masa 12',
    status: 'accepted',
    note: 'SaaS ölçeklenme mentorluk seansı.',
  },
];

export const initialAdminLogs: AdminLogItem[] = [
  {
    id: 'log-1',
    timestamp: '14:22',
    adminName: 'Elif Kaya (Operasyon Lideri)',
    action: 'Oturum 15 dk geciktirildi ve 142 kullanıcıya anlık bildirim iletildi.',
    target: 'Kendi Yapay Zeka Modelini Eğitmek (Lab C)',
    type: 'session',
  },
  {
    id: 'log-2',
    timestamp: '14:10',
    adminName: 'Sarp Demir',
    action: 'Kapasite uyarısı duyurusu yayınlandı.',
    target: 'Tüm Katılımcılar (Zone B)',
    type: 'announcement',
  },
  {
    id: 'log-3',
    timestamp: '13:40',
    adminName: 'Elif Kaya',
    action: 'Yeni stant konumu haritada pinlendi (A-102).',
    target: 'Cognitive AI Labs',
    type: 'booth',
  },
  {
    id: 'log-4',
    timestamp: '12:15',
    adminName: 'Burak Yalçın',
    action: 'Salon kapasite limiti güncellendi: 400 -> 450.',
    target: 'AI & Derin Teknoloji Sahnesi',
    type: 'stage',
  },
  {
    id: 'log-5',
    timestamp: '11:00',
    adminName: 'Elif Kaya',
    action: 'Konum takibi çalışma saatleri başlatıldı (08:30 - 19:30).',
    target: 'Sistem Ayarları',
    type: 'system',
  },
];

export const initialEventSettings: any = {
  eventName: 'Take Off İstanbul Girişimcilik Zirvesi',
  edition: 'Take Off İstanbul 2026',
  eventDates: '24-27 Ekim 2026',
  venueName: 'Lütfi Kırdar Uluslararası Kongre ve Sergi Sarayı (ICEC)',
  venueAddress: 'Harbiye, Gümüş Cd. No:4, 34367 Şişli / İstanbul',
  startDate: '2026-10-24',
  endDate: '2026-10-27',
  logoUrl: '/assets/takeoff-logo.svg',
  // Admin krokiye elle çizdiği duvar çizgileri — bkz. types/admin.ts > FloorPlanWall.
  floorPlanWalls: [],
  openingTime: '08:30',
  closingTime: '19:30',
  locationTrackingStart: '08:30',
  locationTrackingEnd: '19:30',
  trackingDisclaimer:
    'Konum verileri yalnızca etkinlik saatleri (08:30 - 19:30) içerisinde salon/zone yoğunluğunu hesaplamak amacıyla anonim olarak işlenir. Hassas GPS verisi saklanmaz.',
  defaultLanguage: 'tr',
  timezone: 'Europe/Istanbul (UTC+3)',
  autoNotifyScheduleChanges: true,
  enableAnonymousZoneTracking: true,
  requireCheckInQr: true,
  notificationTriggers: {
    autoSessionReminders: true,
    autoCapacityAlerts: true,
    autoMeetingReminders: true,
  },
};

// Aliases for unified imports
export const initialSessions = initialAdminSessions;
export const initialAdminStages = initialStages;
export const initialAdminBooths = initialBooths;
export const initialAdminAttendees = initialAttendees;
export const initialAdminMeetings = initialMeetingRecords;
export const initialMeetings = initialMeetingRecords;
export const initialAdminAnnouncements = initialAnnouncements;
export const initialZoneDensity = initialZones;
