import type { VenuePoint } from '../types';

// Etkinlik kat planı için statik gösterim verisi. Gerçek GPS/zon entegrasyonu
// ayrı bir aşamada `zones`/`stands` tablolarına bağlanacak (bkz. supabase_schema.sql).
export const venuePoints: VenuePoint[] = [
  {
    id: 'hall-a',
    name: 'Ana Sahne (Hall A)',
    type: 'stage',
    floor: 1,
    x: 48,
    y: 35,
    density: 'Yoğun',
    description: '1500 kişilik ana konferans ve panel sahnesi. Keynote ve açılış oturumları burada yapılmaktadır.',
    currentEvent: 'Geleceğin Teknolojileri ve Yapay Zeka Vizyonu (09:00 - 09:45)',
  },
  {
    id: 'hall-b',
    name: 'B Salonu',
    type: 'stage',
    floor: 1,
    x: 75,
    y: 65,
    density: 'Normal',
    description: 'Girişimci sunumları, B2B toplantılar ve özel keynote salonu.',
    currentEvent: 'B2B Toplantı Seansı & Networking',
  },
  {
    id: 'salon-3',
    name: 'Salon 3',
    type: 'stage',
    floor: 1,
    x: 28,
    y: 48,
    density: 'Normal',
    description: 'Yatırımcı panelleri ve girişimcilik oturumları salonu.',
    currentEvent: 'Girişimcilik Ekosisteminde Yatırım Stratejileri',
  },
  {
    id: 'lab-c',
    name: 'Lab C (Workshop)',
    type: 'stage',
    floor: 2,
    x: 35,
    y: 28,
    density: 'Sakin',
    description: 'Uygulamalı teknik atölyeler ve yapay zeka workshop laboratuvarı.',
    currentEvent: 'Kendi Yapay Zeka Modelini Eğitmek (15:30)',
  },
  {
    id: 'fuaye',
    name: 'Fuaye & Kafe Alanı',
    type: 'food',
    floor: 1,
    x: 55,
    y: 52,
    density: 'Yoğun',
    description: 'Networking masaları, kahve ikramı ve sponsor stantları alanı.',
    currentEvent: 'Serbest Networking & Kahve İkramı',
  },
  {
    id: 'vip-lounge',
    name: 'VIP & Yatırımcı Lounge',
    type: 'networking',
    floor: 2,
    x: 68,
    y: 30,
    density: 'Sakin',
    description: 'Birebir yatırımcı görüşmeleri ve özel toplantılar için ayrılmış sessiz alan.',
    currentEvent: 'Özel B2B Eşleşme Seansları',
  },
  {
    id: 'booths',
    name: 'Girişimci Stantları',
    type: 'service',
    floor: 1,
    x: 40,
    y: 72,
    density: 'Normal',
    description: '100+ yerli ve küresel teknoloji girişiminin demo stantları.',
    currentEvent: 'Ürün Demoları & Tanıtımlar',
  },
];
